# Student Academic Risk Prediction Using Logistic Regression

## Project Goal

The goal of this project is to develop an interpretable machine learning
system that predicts whether a student is academically at risk using
student demographic, academic, behavioral, and socioeconomic information.

The project will focus on Logistic Regression and will study:

- The mathematical foundation of Logistic Regression
- Implementation from scratch using NumPy
- Data preprocessing
- Gradient descent
- Learning rate and convergence
- Regularization
- Hyperparameter tuning
- Classification thresholds
- Model evaluation
- Coefficient interpretation
- Error analysis
- End-to-end deployment

## Research Perspective

The project will not only focus on achieving high predictive performance.
It will investigate how different modeling decisions affect the behavior,
performance, and interpretability of Logistic Regression.

In [2]:
import pandas as  pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as snd 

from pathlib import Path

pd.set_option('display.max_columns', None  )
pd.set_option('display.max_rows', None  )

## datasets imports

In [3]:
data_path = Path("../data/students.csv")

df = pd.read_csv(data_path)

df.head()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0

In [4]:
df.shape
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")

Number of rows: 2392
Number of columns: 15

In [5]:
df.head()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0

In [6]:
df.tail()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
2387,3388,18,1,0,3,10.680555,2,0,4,1,0,0,0,3.455509,0.0
2388,3389,17,0,0,1,7.583217,4,1,4,0,1,0,0,3.279150,4.0
2389,3390,16,1,0,2,6.805500,20,0,2,0,0,0,1,1.142333,2.0
2390,3391,16,1,1,0,12.416653,17,0,2,0,1,1,0,1.803297,1.0
2391,3392,16,1,0,2,17.819907,13,0,2,0,0,0,1,2.140014,1.0

In [7]:
df.sample(5, random_state=42)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
1004,2005,15,1,2,4,0.135763,17,0,2,0,1,1,1,1.427724,4.0
196,1197,16,1,0,4,1.989925,0,0,1,1,0,0,1,3.117354,1.0
2342,3343,15,0,0,0,10.588715,15,0,3,0,0,0,1,2.037769,2.0
1708,2709,18,1,1,2,16.208658,1,0,3,1,0,0,0,3.548521,0.0
435,1436,18,0,0,0,3.576821,27,0,1,0,1,0,0,0.248977,4.0

In [8]:
df.columns.tolist()

['StudentID',
 'Age',
 'Gender',
 'Ethnicity',
 'ParentalEducation',
 'StudyTimeWeekly',
 'Absences',
 'Tutoring',
 'ParentalSupport',
 'Extracurricular',
 'Sports',
 'Music',
 'Volunteering',
 'GPA',
 'GradeClass']

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2392 entries, 0 to 2391
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          2392 non-null   int64
 1   Age                2392 non-null   int64
 2   Gender             2392 non-null   int64
 3   Ethnicity          2392 non-null   int64
 4   ParentalEducation  2392 non-null   int64
 5   StudyTimeWeekly    2392 non-null   float64
 6   Absences           2392 non-null   int64
 7   Tutoring           2392 non-null   int64
 8   ParentalSupport    2392 non-null   int64
 9   Extracurricular    2392 non-null   int64
 10  Sports             2392 non-null   int64
 11  Music              2392 non-null   int64
 12  Volunteering       2392 non-null   int64
 13  GPA                2392 non-null   float64
 14  GradeClass         2392 non-null   float64
dtypes: float64(3), int64(12)
memory usage: 280.4 KB

In [10]:
df.describe(include="all").T

,count,mean,std,min,25%,50%,75%,max
StudentID,2392.0,2196.500000,690.655244,1001.000000,1598.750000,2196.500000,2794.250000,3392.000000
Age,2392.0,16.468645,1.123798,15.000000,15.000000,16.000000,17.000000,18.000000
Gender,2392.0,0.510870,0.499986,0.000000,0.000000,1.000000,1.000000,1.000000
Ethnicity,2392.0,0.877508,1.028476,0.000000,0.000000,0.000000,2.000000,3.000000
ParentalEducation,2392.0,1.746237,1.000411,0.000000,1.000000,2.000000,2.000000,4.000000
StudyTimeWeekly,2392.0,9.771992,5.652774,0.001057,5.043079,9.705363,14.408410,19.978094
Absences,2392.0,14.541388,8.467417,0.000000,7.000000,15.000000,22.000000,29.000000
Tutoring,2392.0,0.301421,0.458971,0.000000,0.000000,0.000000,1.000000,1.000000
ParentalSupport,2392.0,2.122074,1.122813,0.000000,1.000000,2.000000,3.000000,4.000000
Extracurricular,2392.0,0.383361,0.486307,0.000000,0.000000,0.000000,1.000000,1.000000
Sports,2392.0,0.303512,0.459870,0.000000,0.000000,0.000000,1.000000,1.000000
Music,2392.0,0.196906,0.397744,0.000000,0.000000,0.000000,0.000000,1.000000
Volunteering,2392.0,0.157191,0.364057,0.000000,0.000000,0.000000,0.000000,1.000000
GPA,2392.0,1.906186,0.915156,0.000000,1.174803,1.893393,2.622216,4.000000
GradeClass,2392.0,2.983696,1.233908,0.000000,2.000000,4.000000,4.000000,4.000000

In [11]:
df.dtypes

StudentID              int64
Age                    int64
Gender                 int64
Ethnicity              int64
ParentalEducation      int64
StudyTimeWeekly      float64
Absences               int64
Tutoring               int64
ParentalSupport        int64
Extracurricular        int64
Sports                 int64
Music                  int64
Volunteering           int64
GPA                  float64
GradeClass           float64
dtype: object

In [12]:
numeric_columns = df.select_dtypes(include=np.number).columns.tolist()

categorical_columns = df.select_dtypes(
    include=["object", "category", "bool"]
).columns.tolist()

print("Numerical columns:")
print(numeric_columns)

print("\nCategorical columns:")
print(categorical_columns)

Numerical columns:
['StudentID', 'Age', 'Gender', 'Ethnicity', 'ParentalEducation', 'StudyTimeWeekly', 'Absences', 'Tutoring', 'ParentalSupport', 'Extracurricular', 'Sports', 'Music', 'Volunteering', 'GPA', 'GradeClass']

Categorical columns:
[]

In [13]:
missing_values = df.isnull().sum()

missing_values[missing_values > 0]

Series([], dtype: int64)

In [14]:
missing_percentage = (
    df.isnull().mean() * 100
).sort_values(ascending=False)

missing_percentage[missing_percentage > 0]

Series([], dtype: float64)

In [15]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [16]:
df["StudentID"].nunique()

2392

In [17]:
len(df)

2392

In [18]:
for column in df.columns:
    print(f"\n{column}")
    print(df[column].unique()[:20])

StudentID
[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014
 1015 1016 1017 1018 1019 1020]

Age
[17 18 15 16]

Gender
[1 0]

Ethnicity
[0 2 1 3]

ParentalEducation
[2 1 3 4 0]

StudyTimeWeekly
[19.83372281 15.40875606  4.21056977 10.02882947  4.67249527  8.19121855
 15.60168047 15.42449631  4.56200756 18.44446636 11.85136366  7.59848582
 10.03871162 12.10142507 11.19781064  9.72810071 10.09865608  3.52823821
 16.25465809 10.8352064 ]

Absences
[ 7  0 26 14 17 10 22  1 11 15 21  9 16 29  2 25 20  5  8 12]

Tutoring
[1 0]

ParentalSupport
[2 1 3 4 0]

Extracurricular
[0 1]

Sports
[0 1]

Music
[1 0]

Volunteering
[0 1]

GPA
[2.92919559 3.04291483 0.11260225 2.05421814 1.28806118 3.08418361
 2.74823741 1.36014271 2.89681919 3.57347421 2.14717163 1.55959452
 1.52007781 1.75158096 2.39678812 1.34152072 2.23217528 1.38440418
 0.46955332 2.39578409]

GradeClass
[2. 1. 4. 3. 0.]

In [19]:
df[numeric_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
StudentID,2392.0,2196.500000,690.655244,1001.000000,1598.750000,2196.500000,2794.250000,3392.000000
Age,2392.0,16.468645,1.123798,15.000000,15.000000,16.000000,17.000000,18.000000
Gender,2392.0,0.510870,0.499986,0.000000,0.000000,1.000000,1.000000,1.000000
Ethnicity,2392.0,0.877508,1.028476,0.000000,0.000000,0.000000,2.000000,3.000000
ParentalEducation,2392.0,1.746237,1.000411,0.000000,1.000000,2.000000,2.000000,4.000000
StudyTimeWeekly,2392.0,9.771992,5.652774,0.001057,5.043079,9.705363,14.408410,19.978094
Absences,2392.0,14.541388,8.467417,0.000000,7.000000,15.000000,22.000000,29.000000
Tutoring,2392.0,0.301421,0.458971,0.000000,0.000000,0.000000,1.000000,1.000000
ParentalSupport,2392.0,2.122074,1.122813,0.000000,1.000000,2.000000,3.000000,4.000000
Extracurricular,2392.0,0.383361,0.486307,0.000000,0.000000,0.000000,1.000000,1.000000
Sports,2392.0,0.303512,0.459870,0.000000,0.000000,0.000000,1.000000,1.000000
Music,2392.0,0.196906,0.397744,0.000000,0.000000,0.000000,0.000000,1.000000
Volunteering,2392.0,0.157191,0.364057,0.000000,0.000000,0.000000,0.000000,1.000000
GPA,2392.0,1.906186,0.915156,0.000000,1.174803,1.893393,2.622216,4.000000
GradeClass,2392.0,2.983696,1.233908,0.000000,2.000000,4.000000,4.000000,4.000000

In [ ]:
for column in numeric_columns:
    plt.figure(figsize=(6, 4))
    sns.boxplot(x=df[column])
    plt.title(f"Distribution of {column}")
    plt.show()

In [20]:
important_columns = [
    "Age",
    "StudyTimeWeekly",
    "Absences",
    "GPA"
]

In [ ]:
for column in important_columns:
    plt.figure(figsize=(7, 4))
    sns.histplot(data=df, x=column, kde=True)
    plt.title(f"Distribution of {column}")
    plt.show()

In [21]:
df['GPA'].describe()

count    2392.000000
mean        1.906186
std         0.915156
min         0.000000
25%         1.174803
50%         1.893393
75%         2.622216
max         4.000000
Name: GPA, dtype: float64